chore: cloudbuild 파일 관련 디버깅 코드 추가

diff --git a/.github/workflows/dev-deploy.yaml b/.github/workflows/dev-deploy.yaml
--- a/.github/workflows/dev-deploy.yaml
+++ b/.github/workflows/dev-deploy.yaml
@@ -57,6 +57,13 @@ jobs:
         with:
           project_id: dev-ongi-3-tier
 
+      - name: 🔍 Debug: show workspace structure
+        run: |
+          echo "Workspace: ${{ github.workspace }}"
+          ls -al ${{ github.workspace }}
+          ls -al ${{ github.workspace }}/.gcp || echo ".gcp not found!"
+
+
       - name: Trigger Cloud Build
         run: |
           gcloud builds submit . \
